version: "3.9"

services:
  web:
    build: .
    container_name: blogs-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: blogs-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: blogs-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
